//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::feeds::Entity as Feeds;
pub use super::posts::Entity as Posts;
pub use super::push_subscriptions::Entity as PushSubscriptions;
