//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::feeds::Entity")]
    Feeds,
    #[sea_orm(has_many = "super::push_subscriptions::Entity")]
    PushSubscriptions,
}

impl Related<super::feeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feeds.def()
    }
}

impl Related<super::push_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PushSubscriptions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
